export const ACTION = {
  TODO_STORED: "TODO_STORED",
  //ACTIONS TYPES
  TODO_SAVE: "TODO_SAVE",
  TODO_START_EDIT: "TODO_START_EDIT",
  TODO_UPDATE: "TODO_UPDATE",
  TODO_DELETE: "TODO_DELETE",
  TODO_SELECT_ALL: "TODO_SELECT_ALL",
  TODO_CLEAR_DATA: "TODO_CLEAR_DATA",
  TODO_SELECT_DATA: "TODO_SELECT_DATA",
  //STORE THE TOD VALUE JUS LIKE USESTATE
  TODO_INPUT_VALUE: "TODO_INPUT_VALUE",
};
